POST https://api.hh.ru/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&client_id=SHBFO6M6V1JQLFFR1E9C84AEO6IDA48BC34CNTK7UN710EDBRQSEKP9D1BRN7C37&client_secret=QS400ERITG7K3G824K4J54SAH6FFTVLHD1E0SQAEVKFR6BA88F14E3CTVPR9BNDU&code=O0C4D7R2BK4U5UMRFJPA3T6V7R5CMED7KQJ7L94DUDQQDFIS17RTBRTC5B8PCT8H
