name: Check HH Responses

on:
  schedule:
    # Запуск каждые 30 минут
    - cron: "*/30 * * * *"
  # Позволяем запускать вручную
  workflow_dispatch:

jobs:
  check-responses:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Create tokens.json
        run: |
          echo '{
            "access_token": "${{ secrets.HH_ACCESS_TOKEN }}",
            "refresh_token": "${{ secrets.HH_REFRESH_TOKEN }}"
          }' > tokens.json

      - name: Run check responses
        env:
          HH_CLIENT_ID: ${{ secrets.HH_CLIENT_ID }}
          HH_CLIENT_SECRET: ${{ secrets.HH_CLIENT_SECRET }}
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_API_SECRET: ${{ secrets.PLANFIX_API_SECRET }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: npm start

      - name: Commit processed responses
        if: success()
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add processed_responses.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update processed responses [skip ci]"
          git push

      - name: Upload processed responses
        uses: actions/upload-artifact@v4
        with:
          name: processed-responses
          path: processed_responses.json
          retention-days: 7
