name: Check HH Responses

on:
  schedule:
    # Запуск каждые 5 минут
    - cron: "*/5 * * * *"
  # Позволяем запускать вручную
  workflow_dispatch:

jobs:
  check-responses:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Run check responses
        env:
          HH_ACCESS_TOKEN: ${{ secrets.HH_ACCESS_TOKEN }}
          HH_REFRESH_TOKEN: ${{ secrets.HH_REFRESH_TOKEN }}
          HH_CLIENT_ID: ${{ secrets.HH_CLIENT_ID }}
          HH_CLIENT_SECRET: ${{ secrets.HH_CLIENT_SECRET }}
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_API_SECRET: ${{ secrets.PLANFIX_API_SECRET }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
        run: npm start
