name: Check HH Responses

on:
  schedule:
    # Запуск каждые 10 минут
    - cron: "*/10 * * * *"
  # Позволяем запускать вручную
  workflow_dispatch:

jobs:
  check-responses:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Download processed responses
        uses: actions/download-artifact@v4
        with:
          name: processed-responses
          path: ./
        continue-on-error: true

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Create tokens.json
        run: |
          echo '{
            "access_token": "${{ secrets.HH_ACCESS_TOKEN }}",
            "refresh_token": "${{ secrets.HH_REFRESH_TOKEN }}"
          }' > tokens.json

      - name: Run check responses
        env:
          HH_CLIENT_ID: ${{ secrets.HH_CLIENT_ID }}
          HH_CLIENT_SECRET: ${{ secrets.HH_CLIENT_SECRET }}
          PLANFIX_API_KEY: ${{ secrets.PLANFIX_API_KEY }}
          PLANFIX_API_SECRET: ${{ secrets.PLANFIX_API_SECRET }}
          PLANFIX_ACCOUNT: ${{ secrets.PLANFIX_ACCOUNT }}
        run: npm start

      - name: Upload processed responses
        uses: actions/upload-artifact@v4
        with:
          name: processed-responses
          path: processed_responses.json
          retention-days: 7
